### ISSUE TITLE
Not working inside Bootstrap 4.4.1 Modals

### ISSUE THREAD

**Issue by sca234** [goodleby/slidinput#1]
Nice project, works good so far except the usage of your script inside of Bootstrap-modals.
I created a fresh html-page only with example-code directly from Bootstrap to test this issue. Everything works fine on the normal page, but inside a modal I get the result als seen in the screenshot.
The input is VERY small and the placeholder text is outside.
![modal](https://user-images.githubusercontent.com/62262318/76793941-537b5a80-67c6-11ea-8b18-d8d45a6c3b20.PNG)

**Comment by goodleby** [comment]
@sca234 Thank you very much for opening issue in order to improve the plugin ;) I will review this ASAP and text here if I have any questions on how to reproduce the problem :)

**Comment by goodleby** [comment]
Sorry for 3 different commits pointing at this issue, I had to update it... :)

**Comment by sca234** [comment]
After a quick test with the standard settings of your plugin I can say: 
everything works fine now inside bootstrap modals.
